[book]
authors = ["erri120"]
language = "en"
multilingual = false
src = "src"
title = "Open Papyrus Compiler"
description = "Documentation for the Open Papyrus Compiler"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/erri120/papyrus-compiler"
edit-url-template = "https://github.com/erri120/papyrus-compiler/edit/master/docs/{path}"
additional-js = ["papyrus.min.js", "x86asm.min.js"]

[output.html.print]
enable = false